// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NoqaX0LH7hO_agmC5CBcQax36aweXvM',
    appId: '1:704119218232:web:44f23fdbec6449ffbac6cd',
    messagingSenderId: '704119218232',
    projectId: 'bellgator-one-four',
    authDomain: 'bellgator-one-four.firebaseapp.com',
    storageBucket: 'bellgator-one-four.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H9rAPsqPcTI7ako7ILU_jlacGguxGns',
    appId: '1:704119218232:android:5622a7ea5e804fc8bac6cd',
    messagingSenderId: '704119218232',
    projectId: 'bellgator-one-four',
    storageBucket: 'bellgator-one-four.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JyOl2DusZ7--Wk5y6AVsXQmAtfYP4c0',
    appId: '1:704119218232:ios:f15c8980cb73ed65bac6cd',
    messagingSenderId: '704119218232',
    projectId: 'bellgator-one-four',
    storageBucket: 'bellgator-one-four.appspot.com',
    iosClientId:
        '704119218232-q6s8i3ko03oo5afmf8khhrbclqffd3ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellgatorOneFour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JyOl2DusZ7--Wk5y6AVsXQmAtfYP4c0',
    appId: '1:704119218232:ios:f15c8980cb73ed65bac6cd',
    messagingSenderId: '704119218232',
    projectId: 'bellgator-one-four',
    storageBucket: 'bellgator-one-four.appspot.com',
    iosClientId:
        '704119218232-q6s8i3ko03oo5afmf8khhrbclqffd3ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellgatorOneFour',
  );
}
